apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.serviceName }}-pdb
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.selectorLabels }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.selectorLabels }}